### ISSUE TITLE
can anyone tell how to load model and use it after training it?

### ISSUE THREAD

**Issue by panwar2001** [tulasiram58827/Information-Extraction-From-Documents#5]
changed this line 

        if (epoch+1)%10 == 0:
            # Save the weights
            model.save_weights(models_path / f'checkpoint_{epoch}.h5')

just trying for dummy data , but it's getting error. Can't load it.

model=Model(vocab_size=25, emb_dim=128, num_heads=8,
                  num_fields=4, num_neighbors=30, padding_val=0)
model.load_weights("data/models/checkpoint_9.h5")

**Comment by reBiocoder** [comment]
please tell me , how to use it?
